minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - vite
  - "@gathertown/webhook-object-sdk"
  - "@gathertown/webhook-object-types"
gitBranchLockfile: true
enableGlobalVirtualStore: true
mergeGitBranchLockfilesBranchPattern:
  - main
  - release*
allowBuilds:
  esbuild: true
packages:
  - "packages/*"
