minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - vite
gitBranchLockfile: true
mergeGitBranchLockfilesBranchPattern:
  - main
  - release*
allowBuilds:
  esbuild: true
packages:
  - "packages/*"
